import requests
import os
import json
from fastapi.encoders import jsonable_encoder

from database import ImageData, UserData

# Configuration
FASTAPI_SERVER_URL = "http://127.0.0.1:8000"  
UPLOAD_IMAGE_ENDPOINT = f"{FASTAPI_SERVER_URL}/upload_image/"
SUBMIT_METADATA_ENDPOINT = f"{FASTAPI_SERVER_URL}/submit_metadata/"

def upload_image_to_server(image_path: str):
    """
    Uploads an image file to the FastAPI server's /upload_image/ endpoint.
    Returns the image_name generated by the server.
    """

    if not os.path.exists(image_path):
        print(f"Error: Image file not found at {image_path}")
        return None

    try:
        with open(image_path, "rb") as image_file:
            files = {"image": (os.path.basename(image_path), image_file, "image/jpeg")} # Adjust MIME type if not JPEG
            # The 'files' parameter in requests automatically handles multipart/form-data
            response = requests.post(UPLOAD_IMAGE_ENDPOINT, files=files)
            response.raise_for_status()  # Raise an exception for HTTP errors (4xx or 5xx)

            response_data = response.json()
            print(f"Image Upload Response: {response_data}")
            if response.status_code == 200 and "image_name" in response_data:
                return response_data["image_name"]
            else:
                print(f"Error: Unexpected response for image upload: {response_data}")
                return None
    except requests.exceptions.RequestException as e:
        print(f"Error uploading image: {e}")
        return None

def submit_metadata_to_server(image_name: str, description: str = None, tags: list[str] = None, user_data: UserData = None):
    """
    Submits metadata for an image to the FastAPI server's /submit_metadata/ endpoint.
    """
    if not image_name:
        print("Error: Image name is required for metadata submission.")
        return False

    metadata_payload = {
        "image_name": image_name,
        "description": description,
        "tags": tags if tags is not None else [],
        "user_data": user_data
    }

    try:
        headers = {}
        token = "nutrinails2"
        headers["Authorization"] = f"Bearer {token}"

        # The 'json' parameter in requests automatically sets Content-Type to application/json
        jdata = jsonable_encoder(metadata_payload)
        response = requests.post(SUBMIT_METADATA_ENDPOINT, headers=headers, json=jdata)
        response.raise_for_status() # Raise an exception for HTTP errors

        print(f"Metadata Submission Response: {response.json()}")
        if response.status_code == 200:
            return True
        else:
            print(f"Error: Unexpected response for metadata submission: {response.json()}")
            return False
    except requests.exceptions.RequestException as e:
        print(f"Error submitting metadata: {e}")
        return False

if __name__ == "__main__":
    # --- Example Usage ---

    # 1. Create a dummy image file for testing (if you don't have one)
    dummy_image_path = "example_images/hand4.jpg"
    if not os.path.exists(dummy_image_path):
        try:
            from PIL import Image
            img = Image.new('RGB', (60, 30), color = 'red')
            img.save(dummy_image_path)
            print(f"Created a dummy image: {dummy_image_path}")
        except ImportError:
            print("Pillow (PIL) not installed. Please create 'test_image.jpg' manually for testing.")
            print("You can install it with: pip install Pillow")
            exit()

    # --- Step 1: Upload the image ---
    print("\n--- Uploading Image ---")
    uploaded_image_name = upload_image_to_server(dummy_image_path)

    if uploaded_image_name:
        print(f"Successfully uploaded image. Server-generated name: {uploaded_image_name}")

        user_data = UserData(sex="male", age=59, factors=["hypertonia"])

        success = submit_metadata_to_server(
            image_name=uploaded_image_name,
            description="Die Beschreibung",
            tags=["left", "index"],
            user_data=user_data
        )

        if success:
            print(f"Metadata submitted successfully for {uploaded_image_name}")
            print("\nCheck your 'submitted_images' directory and 'database.json' file.")
        else:
            print(f"Failed to submit metadata for {uploaded_image_name}")
    else:
        print("Image upload failed, skipping metadata submission.")

    # Clean up dummy image (optional)
    # if os.path.exists(dummy_image_path):
    #     os.remove(dummy_image_path)
    #     print(f"Removed dummy image: {dummy_image_path}")